# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/lisa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lisa)

$(call add-radio-file-sha1-checked,radio/abl.img,003840b95b246bd15af35cd181db36f3d3e5b1bd)
$(call add-radio-file-sha1-checked,radio/aop.img,fc1ca4e06b6bb79cf46f43eec0aeeb413dee7c00)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,166d8e7ab82b7374eff289bd063e1c6b32dfad66)
$(call add-radio-file-sha1-checked,radio/cpucp.img,4a9a479f0e841968b27374793fe6a02107ccf4f5)
$(call add-radio-file-sha1-checked,radio/devcfg.img,8d5d8fd2b9d34564a8692333b18d28c754a7a6a9)
$(call add-radio-file-sha1-checked,radio/dsp.img,c21e6e8bf124b76385a8f00c14baf084e9623352)
$(call add-radio-file-sha1-checked,radio/featenabler.img,b80d6e5e8c8732dd5ad8303515eacd81280896ed)
$(call add-radio-file-sha1-checked,radio/hyp.img,df48ed32b520b9ac754f6e22781f869d9db9ea65)
$(call add-radio-file-sha1-checked,radio/imagefv.img,42cf8f5940e934703f96014643ea2b10aed9d774)
$(call add-radio-file-sha1-checked,radio/keymaster.img,72f2086d7a380f53b60daed4d5438360936c4952)
$(call add-radio-file-sha1-checked,radio/modem.img,23a74954d7c27e3918b3b0b499d4626f12ed13f6)
$(call add-radio-file-sha1-checked,radio/qupfw.img,2d192215c93a692f658c878918a34a6383963961)
$(call add-radio-file-sha1-checked,radio/shrm.img,d341b4972102def64c546d328442e65a85e10f1b)
$(call add-radio-file-sha1-checked,radio/tz.img,b84ba5c6d77558fcfd189c9ac8292bc3afb71db1)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,a5351ff7cdb8165a1cbbb61828ec675fa3817f2a)
$(call add-radio-file-sha1-checked,radio/xbl.img,89d97393450c9cf8f317903c4a8872d288c1fc6f)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,d74da6a6b0d2efcf5565927430bd54eea83d24c2)

endif
